### ISSUE TITLE
Ring credentials required in cloud-based polyglot

### ISSUE THREAD

**Issue by ajm1635** [UniversalDevicesInc/ring-nodeserver#1]
Limiting this node server to Polyglot Cloud poses risk to Ring accounts which include the Ring security system.  Someone gaining access to those credentials would have the account information, which includes the address of the home, and the ability to disable the security system.

**Comment by BenoitMercier** [comment]
Ring requires a postback url to send events to. Polyglot Cloud can handle this, but not polyglot.
