### ISSUE TITLE
Not auto upgrading to 1.1.2

### ISSUE THREAD

**Issue by imrahnee** [UniversalDevicesInc/ring-nodeserver#2]
Stopped and restarted NS but it is not updating to 1.1.2...still shows 1.1.0

**Comment by imrahnee** [comment]
I appears that it did upgrade however the PGC Dash still shows it as 1.1.0.  I have control of my floodcam lights now and that was part of 1.1.2.  

Current Status: Connected
Current Version: 1.1.0
Time Started: Nov 9, 2019, 2:51:56 AM
Uptime: 8 Hour(s) 9 Minute(s) 27 Second(s) 
Current Worker: ring-0021bxxxxxxx

**Comment by BenoitMercier** [comment]
This is Polyglot Cloud bug display issue.
